### ISSUE TITLE
Dependancy WX Converter not mentioned

### ISSUE THREAD

**Issue by kindleton** [irshadbhat/python-hutrans#1]
The readme doesn't mention of WX converter being a dependancy for this module. I think you can add that too :)

**Comment by irshadbhat** [comment]
See this line in dependencies:
python-hutrans requires sklearn, cython, SciPy and python-converter-indic.

python-converter-indic is WX converter

**Comment by kindleton** [comment]
oh! my bad!
Close the issue by the way :D
