### ISSUE TITLE
Support for Python3+

### ISSUE THREAD

**Issue by GokulNC** [irshadbhat/python-hutrans#2]
Hello @irshadbhat 
Hope you're doing great.

Would it be possible to support this work for Python 3+?
I even tried it on Python 2.7, but was facing installation issues.

I would be great if you can fix this library, it will be very useful for many people,

Thanks!

**Comment by irshadbhat** [comment]
Hi,

Try [indic-trans](https://github.com/libindic/indic-trans). It has both python 2 and 3 support. It supports cross transliteration of most of the Indian languages and English.

**Comment by GokulNC** [comment]
Thank you.. You can also mention that in the README of this repo.
